version: '3'

services:
  db:
    container_name: postsDB
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: api-posts
#    image: jibber-jabber-posts_api #Queda buildeada del docker-compose build, eventualmente pusheada en un repo publico.
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file:
      - .env.production
    depends_on:
      - db

volumes:
  pgdata: